### ISSUE TITLE
No data in Kubuntu

### ISSUE THREAD

**Issue by jarnalyrkar** [jorge-barroso/harvesttimer-qt#12]
I got the application running on Kubuntu 22.10, with KDE environment.
The first time I opened the application I was prompted to log in to Harvest, and did so.

However, when I opened the application a second time, the dropdowns are empty.
I can't see previously tracked time either.

If I run the program as sudo I get some messages:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
/usr/bin/xdg-open: 611: kfmclient: not found
/usr/bin/xdg-open: 491: test: Illegal number:

**Comment by jorge-barroso** [comment]
If you run it without sudo, do you get any logs? Also, just to confirm, you installed it via the .deb file right?

**Comment by jorge-barroso** [comment]
Also, can you double-check whether you have a qt6 installation? KDE will still use Qt5 until apparently next summer and Harvest Timer uses Qt6 Network libraries

**Comment by jorge-barroso** [comment]
If you can answer both questions it'd make finding the issue easier, but in the meantime, you can try the following:
`rm ~/.config/Harvest\ Timer\ Qt/*` 

And try the following binary, it's a pre-release that contains login fixes
[harvest.zip](https://github.com/jorge-barroso/harvesttimer-qt/files/10237295/harvest.zip)

**Comment by jarnalyrkar** [comment]
I'm sorry for disappearing! I've since fixed my notification settings in github.

I installed Qt6 from their online installer, and now the harvest-linux-x86_64 executable shows gui-components.  The exe in the zip you sent here says that Qt_6.4 is not found. The last part is probably me not adding the correct location to PATH.

- The program shows tracked time for the whole company (~ 15 people), and not for me specifically. Is there a way to change this?
- If I try to add a new entry, the dropdowns are empty, so no projects or tasks are showing.
- I'm also not able to edit existing entries ("Could not find project" message)

**Comment by jorge-barroso** [comment]
About the missing data (projects in dropdowns, etc.) and just to confirm, have you tried running the following command?
`rm ~/.config/Harvest\ Timer\ Qt/*`

I'm investigating the first point you've reported :)

**Comment by jarnalyrkar** [comment]
Yep, I tried to remove the config files - no difference, I'm afraid

**Comment by jarnalyrkar** [comment]
Yes, I ran that command, but still no projects or tasks in dropdowns.

**Comment by jorge-barroso** [comment]
Reach out by email if that's okay, I'd gladly help you, but my resources are limited at the moment, and this sounds like a very particular case, so I might need some info you probably don't want to disclose here.

**Comment by jorge-barroso** [comment]
I didn't mean to close this automatically, but the latest 1.0.4 should have fixed these issues :)

**Comment by jorge-barroso** [comment]
Received confirmation that the fixes worked 😄
